name: CI for python cloud application
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependency
        run: |
          make install
          
      - name: Lint
        run: |
          make lint
          
      - name: Run test
        run: |
          make test
          
      - name: Format files
        run: |
          make format
